---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDW9UCGUqqYZVkbizzbz5M8YnhJF1Wm7rkJG1wVBKiN7Oq50/eqQe0hVtTj+OoE14BLjwd6FlhZOZXdKqR6joThiv4Y+dUmLk3ztZDL2xEH5HjYvDOqpMbx4HHhwovQnb+BdGqAxTRCijYMuCM8RxZRUsJbDyEyxg8ZGTuX62TQBekFvkApkrd1+2C3rB+Db9ENgpPcv7U5hiU14WkHtWsfjWopdjZVe8vQzvoWcp6MVSBqggH4VeE7E+og1v9oUznWF6kxiAU7GzhmMYYpncUeBGYJu8uU8MySKkN1z3uvJdTz7RMAniUCTt1OvdtVJCHCu9PrDnaNAEsW8BLcTdoKUBtLWPFwVNGgUHiR4QSu55sDNKfXoX0pE5fPHTuzSN0wPhC7WM2m96Jjt3jm8xbx1v/FQSIr8lOji9IWyc7GGt2SQBNFYycDHEF+lXnG0aTHO6UpOKkCUkqWHfOdUyAWfzgfOUzqH/XaM1tCLQ16dvjAhdWvwxz0lPJfz6qh6EnzfIgxknNUK3embq5EgS7Co1HXPNPNKd2O1PBtspwyS2MA2uYTGeX/ICr6/5HeC+z7YZCGEVJI4ppQT5v/lTdNWvS+OZsBC4zrXuQ/MIm9hpUdA7NLb5PE21FP2CuCAAMOLqb36LVL8XH5XjubJPX+oZez3Ckk1KtczyFHRPmrBwhwRLj25l7HKX3n4nEyZlqHaIA8ykCXllxgYgpGdb91I6r+nUHxvgeZ9DhpQvUdUZ/pmSydqj4BjE/Jp++OkbbRBSckYHEBNGw+KDEm6SKQ
    POSTGRES_USER: AgAnRWXJxYBWX+8L6YOzZAPfSOJE24PJu7uDKIhHx9+2nJjgN7ggwTX+h5GtGS2pCW86jRVi+02hEcCGNVy37K02Z3I3SlEko3rFShLISGEqrqPURp6S6vVOEWNqc/RweHTC8aV8tb/ti8fLSXEh/POJ+57eigjsUIf9OFUux7484RA2WpcNHKwbx8EGyT1YSHFaTk7RrCw3yuKOh8/oKiYfkluA5k4rAuHareunA8n6NprFCeHzgHuc3IHLi1EzRodRi7mQzFPQUgNfqyIMGXy0vkHjXg/lqPs3MWNEhdRehs0kAFaYGO5SwtqXi9OLblj7koD1JRocQqPb+5r0v1O4gJS8YBrNcwAQbDD9q6k90pK4p8zwrJwMtjRkpsQrpiR/nF92GRWGR325uo3MlZ9yseRfsp1hLCn73CFDgf1fjjpUL2Enk3utIDdVIb/PMs+H40KTBWIfIEkE5K5kQe3/lXZ8mOhre+Z/oQQErQrlpWVyLSEwCdlaqn8jFXunpKIf9gSVpsUrmAIglHNft/Klh/OY3PNxC6QTVIyK8QuUmYU4N7+pnMCT9JNRslxmMmyy1G12yiUICIpB88w4xfdzITDDlawIBzbktOUwLpZAYmzzEC55mr0CxkH2aTllOO1lnGuA2VSrnml0dYUf0ImiDTFJQnDMrDblIq0amOnlcyC0m2l6zg9T8/hmxqMR6sHcfHxohigINA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque