---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: 132b-project-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCK9v5FPIk3UTY05mja6R3Ow4Y7KB7YaKtPLE4Yc3H209t9AlvbO1x0SiyH0FXhb2qhapTKYrMVt3fKahb/xmDhqBqKLDqm79Q71tyjI2beb7S0DjUD28hqCG6Qz/6ZaumIREfHFbZ+y27zgDjsewOr5ppIpi1PHebvILWlyTYypJpBQwPc2AOsBqHu5hb3hGV4UIsAtkNd8fvaImU8TUAiPUJm9qxBFSm9AVgEH4v08QQelQeU/F6MeKWJmgL09BWXxt9DZj2k+R/XYEyMn9alEzEP3jo8MEZY4HdQLJZVbtIwAwD9e1lnvjPh9fBhRJcsXXDxkIV31TfD4rY3O2m88xq1YZT698cmEt9JU6PxmnZKRX5cH+jLB9PoO3x+ywTCGQNtFxKf6p0Vs1PtPeti1KKVch0O4lA3++HCas7HZVoomCqWEo93YDOMKjHNj3BA2mO1NCKOuHpidOR+98StT/qNvsBFJbTdIpT89rbQjt3nPB+JoN38LbuHGDzwCYuhlMWoXr0I31lFV78xbiR5PbM7Gn+ysgQmbtXBPHooodHied38fH3BrxXEVepEKH8syJICoT1e8Q4KV4Q5cFI4aDJnEC1mWLYtFV1NKr5lytGpqSTPvZNw5rmA10epmuEmZOf5clfDKiqCPAXFYiCLWVE4xImbx1TtuOi5ytW/3RYq8DuwlOBfDpKNQGH3ffnAitESMKmvwi+YXanUqiITxNhb6KUL72b7KGYoNANON3o5DuYncElYBQlLKASSgVum40KUTkW98EbJAtQrNvVmGEWchJze+wHWWbvlnwuj7I3eSGEWK/xp5yK78+Q=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: 132b-project-secret
      namespace: arc-runners