apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: rooty-dev-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCjtIpaTnaf97P+UfXoSYogyigx2y1zswin3ldMZfo68HICqQfGqmpV65oLTmW4VxhuO959KJ3UyC0/bj2zjEjw/KVCkYi7Q9MWl+zNgyfswUBu4CYnMUCWn5JLItG7jYN5iRj15u3rCC6/4xct8fMBxW/ccfjIb50S0U59oTONDQ6CxZhTEemaB42fnbs3aQVLwZsup+goH4/S7Skm9y9PXwcCLBYX/iB+v0FDRcgCkm4tDh8npFEp8SfWow2UFRWuZAhbaIQuA7say23tTgnH1JZl8heW4Z5nTFFCKzZIgGQbKEBzBNy2FAVYmKQRpmz9ksL7c0fwtrjBmidPw+elosY1rdy7shBnhQNm4fYlSMhYm1VeiPeOMXbujBNjhWi4vo5Nz2mjeUcnKarABJqHloiE8/VcvbSiGGaHH2ubKuvo+mZezla51sT3mnqb2ITxSNvRXsKazxhhy5JcLtUl8Hhp1HBAErYIBoINsBWdFoM6EYmp3kvox/KZo9cO8mTZ/qY+pjCVeDOIVjBybq2L6TKGliMq7xnjtI6COgi2hVrh/pX3fMz4wbach7cP6HZN6EeizdmroU34BmrDuPCnjE9qknSaqgQJM2tI0VKqlqlVqrbJ0zrFvjZdxBU0CYgDSo4CJzhMOEPcxkBtqbtYf0gXi0WRoG8CVmi5x5gnjAiMKro2OWA/zRobXyiatTmOsh5+KXnzefABMKjSPxXjMqPGMWdwMcWpiaYPJcmvmgwwVqNhfRkwHirS5raT1yUKeHdeF9OYOWdsR3xgn7UkenvSkRKork+RGnOLbVQERIBlRtVhnG2plPvRYpE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: rooty-dev-secret
      namespace: arc-runners