apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: arc
  namespace: arc-system
spec:
  targetNamespace: arc-system
  createNamespace: true
  version: v0.9.0
  chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
