---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: authentik-secret
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgCZ/6QEux+/04G0u7lEqfFCY5thXeCNAS7KgUyKwgZbDxPil++wf0us0QkHqqvHmbU1Gyzez1WRbbsxy97+a1AVDoTVupu/XE6aLkz2ReaQnUATc1Cn6s2NFxBYI6ydh4n1n1cD7GV6PGMVpXMwiyVqJvSTbp/1ZB4BnDZAYG35H64VzH0i1zsZiKty9AIhMZHCsYkFv8X9oLseUiJ695Seh5P+4KeyCiU08S5+SSp5V59/d3fGCt9dBwQ2+7du7KgqnYEQt/xw77CEM9KRwqIGcdAq/qbH67omQRynfgCgMQMIyV5E27RRBp7H1DmD06mfRudpREtEQestB7MeuoDEaTDpY0cOwTvSDFOnMwlzUUeIEIm30DsAIhsqfKw32T0M55KS0QSMjCbjRg54yWXPk4dWdynpyLkHw0zJoMitrOIUY88bfsgc4fckbwGE1X83NjsyvdPjj3adL/zOXbRD/L7qZqpPSOHM51AzUkJHm027f7+pzTM/mh3BPTfND7tIA2j6XUXlf7OlMq1/P7d+S3RfNBFbaWtqspP1oqet5Tm5i4qSEI+aZwqHmRsymBGII7q6UXOFWqjzYJJzz9S2xKxicD9KgVU2HYu1nPQd8P5S5UpT6aHDz3WjtEEOp96UEPpagCMDFGxlQHWsmYEeF62j6iq4poaaTJfSkfHyGV3zXBgnFd8DTcXAM3xzz2fVFodIwN8A0E23W5QNM7TYwEvcFI4KhOXKTZYNC3iZMIoss0RUtFvbhJogUqN3tprMKQ==
    POSTGRES_PASSWORD: AgCvMPLvk0Ji8VSuu+D0CcQj30YKSDxRXc9GxAwIcxlgHHYrE/L4AgUKkNyiHtFhXDLWA8Ddr5WIkn6OQSDS0hMKxuKL9FvHsM/wH9L1wHaWJlfwcDT2um+4y4lbnNzFuErwVt1HLKqhcugUvBrp3x6RYkHCK6bn08yux+AwJOIc6+I2nhBVXNuNdjiGioO9iM7F/WdPjokLuwadjYMhY5IS0YscYyeTPw+hYx3VsR2EYnK6VTDhl8oLOjFyNxS131GU5FU0Yzj1Ow2+bvcNDCgr+x498Dq1KRa/2bdOc3dcCSdLPcbYGuv5hMTQbwqutDZbO8O5jFs1BAmpQCw34m1Y+hfH8LcOXYvm2sj06RZ2ZBppT2MyxXtLqNpVZlRRhERlpJHXQ/Z84M+otieaYiqRnggvSnXmvO4l1AOqjD4BIR1H4PoOmn5TDCo8QmAtmSzQRHcOYh7y+FssxQJgzf3E+5TLcEKJWyiqtTha0q60G4Ez4PyQN4NFeZ9v2Hssdapeg2GIYQfq/JfkSxQmOfUes0XO1TbCnweVRYsXohRcEunxo8WG0gWaZ5HtVpS00aViI3MGb/PMpQuF8CRmRFq58VgzOXc2aRoMVZvGguS+qjypQ6noEqkRm5SFNPgB6LdewOrvrqNaKixvN9jWetZHG1UHktl2A3IFXyyTKZmF0RLkE4OcY06ovcNWOXh807l804gmqQrEVJgQ5NFB89KHynoWyeL3dPtBbWd+9BMo2DD27Hox/s8YtN2j9ZTTR+o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: authentik-secret
    type: Opaque
