---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAIgMIRzjbOJh0KV3uRnNNFk5GO6ZRao6OoOXnn+MRwvqnObIjLAnZCRDOsguqzi7fY2+j7cpr+ZQqa6TOC+TrTfzg7vAjpiLYpO4lxIfdx2x3HZg08TANINtVuoTw3RpU9O7YogmSMV5sghQIaRdzDlw/FLJgkFuApcyc9MHNm1cZrchaC9+vxKR1NyMoz89/awzebyW/4gKSdT9N5+fIpXEYCIGEycNUkpSnxIFPmyKqInjUnda3vFBTzseMN5wXaO5/okvuOWefBf/z9Y9JxpqUMhVKjP4XUslaVZerEb9ztxKu/SsF8KQzJvQFIp5idbvzwZlAQzLDtQaz49T8NuV2rqfSEqYWZAoFA3BAf0kmt9z+wd5IL2cgck9Kzrnxw1/MchVMgoTvZs77IyspIoTqAwQoGjE6sNd5ev/dO2HSS8ETuMGJIt6+ToBNqCNcCd0OOCQ+e+45/vG+Pbp6B1+1tZE5YuvS8Bzvob3X6/KWCYnOnuVAOb9XMKNo9fjk4UHkDnXLV05uaMOC9wLWmXWyPPG9KbSZU0nCRr48mdHZnctiGRhJUdWS/JEw2d5Tp4vjx1xBAPFVKkZtbfthuUBBq7RwjLN8OxEKAQY1USDBXc6rz0njvSg2a6uwOjrZidmOjRsmHJh/jbxfNk0FZ80D/+wLrmPXMAC2CioHPcZ5+SWVO9Yyg9b3o8qqplCRkWYg5A+wCvr3EIZEC/LdKK7GhMx5MlfGCR3tEsiEzm2l4m6P5vh9naVzVF36r2iXa7+YvsSD28bxFJarPE/kGmWz1raS4y7N0vhPd3PrpSY5Ck1ZpgdDx31xNZbBgnFjfM8M7I0pXFybM6KVt+vnpanax7AgpIQcRnVFINVQt5m/8OCeBHaSrEzK0SgcHtfrfWS+wXU4d5ncJ6UnC0/TlaQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-credentials
      namespace: cloudflared
